In [15]:
# 라이브러리 사용
import pandas as pd
import tensorflow as tf

# 보스턴 집값 예측

In [17]:
# 과거의 데이터를 준비합니다.
path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston = pd.read_csv(path)
boston

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [18]:
# 종속변수, 독립변수
ind_val = boston[['crim','zn','indus','chas','nox','rm','age','dis','rad','tax','ptratio','b','lstat']]
dep_val = boston[['medv']]
print(ind_val.shape, dep_val.shape)

(506, 13) (506, 1)

In [22]:
# 모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X) #10개의 노드, 활성화함수 swish
Y = tf.keras.layers.Dense(1)(H)

model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [23]:
# 모델의 구조 확인
model.summary()

Model: "functional_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_3 (InputLayer)         [(None, 13)]              0
_________________________________________________________________
dense_2 (Dense)              (None, 10)                140
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 11
=================================================================
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________

In [26]:
# 데이터로 모델을 학습(FIT)합니다.
model.fit(ind_val, dep_val, epochs=1000, verbose=0)
model.fit(ind_val, dep_val, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 438us/step - loss: 12.4056
Epoch 2/10
16/16 [==============================] - 0s 375us/step - loss: 12.2376
Epoch 3/10
16/16 [==============================] - 0s 375us/step - loss: 13.1400
Epoch 4/10
16/16 [==============================] - 0s 438us/step - loss: 13.2558
Epoch 5/10
16/16 [==============================] - 0s 375us/step - loss: 12.6716
Epoch 6/10
16/16 [==============================] - 0s 375us/step - loss: 13.2503
Epoch 7/10
16/16 [==============================] - 0s 438us/step - loss: 12.5165
Epoch 8/10
16/16 [==============================] - 0s 375us/step - loss: 12.8858
Epoch 9/10
16/16 [==============================] - 0s 375us/step - loss: 12.9915
Epoch 10/10
16/16 [==============================] - 0s 375us/step - loss: 12.7006

In [27]:
# 모델을 이용합니다.
print(model.predict(ind_val[:5]))
print(dep_val[:5])

[[31.987745]
 [21.650482]
 [31.615322]
 [34.846603]
 [31.179678]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

# 아이리스 품종 분류

In [32]:
# 과거의 데이터를 준비합니다.
path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(path)
# 원-핫 인코딩
iris = pd.get_dummies(iris)
iris

     꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0     5.1  3.5    1.4   0.2          1              0             0
1     4.9  3.0    1.4   0.2          1              0             0
2     4.7  3.2    1.3   0.2          1              0             0
3     4.6  3.1    1.5   0.2          1              0             0
4     5.0  3.6    1.4   0.2          1              0             0
..    ...  ...    ...   ...        ...            ...           ...
145   6.7  3.0    5.2   2.3          0              0             1
146   6.3  2.5    5.0   1.9          0              0             1
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

[150 rows x 7 columns]

In [34]:
# 종속변수, 독립변수
ind_val = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dep_val = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(ind_val.shape, dep_val.shape)

(150, 4) (150, 3)

In [43]:
# 모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)

model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [44]:
# 모델의 구조 확인
model.summary()

Model: "functional_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_5 (InputLayer)         [(None, 4)]               0
_________________________________________________________________
dense_7 (Dense)              (None, 8)                 40
_________________________________________________________________
dense_8 (Dense)              (None, 8)                 72
_________________________________________________________________
dense_9 (Dense)              (None, 8)                 72
_________________________________________________________________
dense_10 (Dense)             (None, 3)                 27
=================================================================
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________

In [46]:
# 데이터로 모델을 학습(FIT)합니다.
model.fit(ind_val, dep_val, epochs=100, verbose=0)

In [48]:
# 모델을 이용합니다.
print(model.predict(ind_val[0:5]))
print(dep_val[0:5])

[[9.99930620e-01 6.94026749e-05 1.06659325e-11]
 [9.99848008e-01 1.51914326e-04 7.32901448e-11]
 [9.99862909e-01 1.37079332e-04 6.79289194e-11]
 [9.99706566e-01 2.93352379e-04 1.96950636e-10]
 [9.99925613e-01 7.43370692e-05 1.14225383e-11]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0